import { Geist, Geist_Mono, Notable, Homemade_Apple } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "@/components/AuthProvider";
import Chatbot from "@/components/Chatbot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const notable = Notable({
  subsets: ['latin'],
  weight: '400', // Only one weight available for Notable
  variable: '--font-notable', // Optional: add as CSS variable
});
const homemadeApple = Homemade_Apple({
  subsets: ['latin'],
  weight: '400', // Only one weight available for Homemade Apple
  variable: '--font-homemade-apple', // Optional: add as CSS variable
});

export const metadata = {
  title: "THRIFT UP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${notable.variable} ${homemadeApple.variable} antialiased`}
      >
        <AuthProvider>
          <div>
          <Navbar/>
          {children}
          {/* <Chatbot/> */}
          <Footer/>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
